### PR TITLE
[MASTER-RELEASE] Metro-Byzantium changes

### PR DESCRIPTION
**Pull request by jwasinger**
EIP 649: block reward reduction

### CODE REVIEW

**Comment by holgerd77** [comment]
@jwasinger ``ommerReward`` and ``niblingReward`` are constants actively being used in the current ``wip/metropolis`` branch: https://github.com/jwasinger/ethereumjs-vm/blob/wip/metropolis/lib/runBlock.js#L10 this will break the whole test setup, not sure what drove you to this decision? I will revert this for being able to work today.

This is generally not a good idea to just remove existing constants from a shared library others might depend on. These constants are not really hurting or being outdated, or are they?

**Comment by jwasinger** [comment]
My reasoning for that was that the ommer reward and nibbler reward can be derived from the Block reward.  Thus, it does not make sense to have constants for them.  I removed these in https://github.com/jwasinger/ethereumjs#wip/metropolis

**Review by holgerd77 — APPROVED** [review]
Everything looks good to me here, have also updated/completed the CHANGELOG (for "Unreleased (Master)").

**Comment by cdetrio** [comment]
Can we remove `ommerReward` and `niblingReward` without breaking ethereumjs-vm/block now? They are indeed outdated after the change to 3 ETH block reward.

**Comment by holgerd77** [comment]
@cdetrio yes, we can, had removed the includes after the change rollback here.

**Pull request merged**
